<?php

namespace Zeeml\Algorithms\Tests\Formulas;

use PHPUnit\Framework\TestCase;
use Zeeml\Algorithms\Formulas\Mean;
use Zeeml\DataSet\DataSet\Mapper;
use Zeeml\DataSet\DataSetFactory;

class MeanTest extends TestCase
{
    public function setUp()
    {
        parent::setUp(); // TODO: Change the autogenerated stub
    }

    /**
     * @dataProvider getData
     * @param array $dataSet
     * @param array $mean
     */
    public function testCalculateUsingDataSet(array $dataSet, array $mean)
    {
        $dataSet = DataSetFactory::create($dataSet);
        $dataSet->prepare(new Mapper([0], [1]));

        $meanFormula = (new Mean())->using($dataSet)->calculate();
        $this->assertEquals(
            $meanFormula->getResult(),
            $mean
        );
    }

    /**
     * @dataProvider getData
     * @param array $dataSet
     * @param array $mean
     * @expectedException \Zeeml\Algorithms\Exceptions\WrongUsageException
     */
    public function testCalculateWithoutUsingDataSet(array $dataSet, array $mean)
    {
        $dataSet = DataSetFactory::create($dataSet);
        $dataSet->prepare(new Mapper([0], [1]));

        $meanFormula = (new Mean())->calculate();
        $this->assertEquals(
            $meanFormula->getResult(),
            []
        );
    }

    public function getData()
    {
        return [
            [
                [
                    [1, 1],
                    [2, 3],
                    [4, 3],
                    [3, 2],
                    [5, 5],
                ]
                ,
                [ [3] , [2.8] ]
            ],
            [
                [
                    [100, 50.1],
                    [110, 55.1],
                    [120, 60.1],
                    [130, 65.1],
                    [140, 70.1],
                    [150, 75.1],
                    [160, 80.1],
                    [170, 85.1],
                    [180, 90.1],
                    [190, 95.1],
                    [200, 100.1],
                    [210, 105.1],
                    [220, 110.1],
                    [230, 115.1],
                    [240, 120.1],
                    [250, 125.1],
                ],
                [ [175] , [87.6] ]
            ]
        ];
    }
}